#ifndef VISIONFLOW_CUDA_ERRORS_H
#define VISIONFLOW_CUDA_ERRORS_H

enum VisionFlowCudaError {
    VF_CUDA_OK = 0,
    VF_CUDA_INVALID_ARGUMENT = 1,
    VF_CUDA_ALLOCATION_FAILED = 2,
    VF_CUDA_COPY_FAILED = 3,
    VF_CUDA_KERNEL_FAILED = 4,
    VF_CUDA_DEVICE_UNAVAILABLE = 5,
    VF_CUDA_ABI_MISMATCH = 6,
    VF_CUDA_INTERNAL_ERROR = 7,
    VF_CUDA_UNSUPPORTED = 8,
    VF_CUDA_RUNTIME_ERROR_BASE = 1000
};

#endif
